// Test data for local development
export default [
    {
       "source":"docker",
       "target":"kubernetes",
       "rank":1,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"vm",
       "rank":2,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"containerd",
       "rank":3,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"container",
       "rank":4,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"ec2",
       "rank":6,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"virtual machine",
       "rank":7,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"lambda",
       "rank":8,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"podman",
       "rank":9,
       "level":1,
       "group":1
    },
    {
       "source":"docker",
       "target":"docker-compose",
       "rank":10,
       "level":1,
       "group":1
    },
    {
       "source":"kubernetes",
       "target":"docker",
       "rank":1,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"ecs",
       "rank":2,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"docker swarm",
       "rank":3,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"service fabric",
       "rank":4,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"docker compose",
       "rank":5,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"serverless",
       "rank":6,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"fargate",
       "rank":7,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"openshift",
       "rank":9,
       "level":2,
       "group":2
    },
    {
       "source":"kubernetes",
       "target":"nomad",
       "rank":10,
       "level":2,
       "group":2
    },
    {
       "source":"vm",
       "target":"container",
       "rank":1,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"docker",
       "rank":2,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"phere",
       "rank":3,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"vdi",
       "rank":4,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"dual boot",
       "rank":5,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"phere client",
       "rank":6,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"server",
       "rank":7,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"kubernetes",
       "rank":8,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"bare metal",
       "rank":9,
       "level":2,
       "group":3
    },
    {
       "source":"vm",
       "target":"vpn",
       "rank":10,
       "level":2,
       "group":3
    },
    {
       "source":"containerd",
       "target":"docker",
       "rank":1,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"cri-o",
       "rank":2,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"runc",
       "rank":3,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"podman",
       "rank":4,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"docker kubernetes",
       "rank":5,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"kubernetes",
       "rank":6,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"moby",
       "rank":7,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"docker engine",
       "rank":8,
       "level":2,
       "group":4
    },
    {
       "source":"containerd",
       "target":"docker-ce",
       "rank":9,
       "level":2,
       "group":4
    },
    {
       "source":"container",
       "target":"vm",
       "rank":1,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"container fluid",
       "rank":2,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"pod",
       "rank":3,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"component react",
       "rank":4,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"image",
       "rank":5,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"serverless",
       "rank":6,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"hypervisor",
       "rank":7,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"ou",
       "rank":8,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"kubernetes",
       "rank":9,
       "level":2,
       "group":5
    },
    {
       "source":"container",
       "target":"codec",
       "rank":10,
       "level":2,
       "group":5
    },
    {
       "source":"ec2",
       "target":"ecs",
       "rank":1,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"lambda",
       "rank":2,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"fargate",
       "rank":3,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"lightsail",
       "rank":4,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"s3",
       "rank":5,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"eks",
       "rank":6,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"kubernetes",
       "rank":7,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"azure vm",
       "rank":8,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"fargate pricing",
       "rank":9,
       "level":2,
       "group":6
    },
    {
       "source":"ec2",
       "target":"docker",
       "rank":10,
       "level":2,
       "group":6
    },
    {
       "source":"virtual machine",
       "target":"container",
       "rank":1,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"docker",
       "rank":2,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"dual boot",
       "rank":3,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"server",
       "rank":4,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"remote desktop",
       "rank":5,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"emulator",
       "rank":6,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"virtual desktop",
       "rank":7,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"bootcamp",
       "rank":8,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"virtual environment",
       "rank":9,
       "level":2,
       "group":7
    },
    {
       "source":"virtual machine",
       "target":"vpn",
       "rank":10,
       "level":2,
       "group":7
    },
    {
       "source":"lambda",
       "target":"fargate",
       "rank":1,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"ec2",
       "rank":2,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"kappa architecture",
       "rank":3,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"ecs",
       "rank":4,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"ec2 cost",
       "rank":5,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"docker",
       "rank":6,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"afr",
       "rank":7,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"kubernetes",
       "rank":8,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"afr chart",
       "rank":9,
       "level":2,
       "group":8
    },
    {
       "source":"lambda",
       "target":"kappa light chain",
       "rank":10,
       "level":2,
       "group":8
    },
    {
       "source":"podman",
       "target":"docker",
       "rank":1,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"kubernetes",
       "rank":2,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"buildah",
       "rank":3,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"cri-o",
       "rank":4,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"docker performance",
       "rank":5,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"singularity",
       "rank":6,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"code",
       "rank":7,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"docker reddit",
       "rank":8,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"containerd",
       "rank":9,
       "level":2,
       "group":9
    },
    {
       "source":"podman",
       "target":"lxc",
       "rank":10,
       "level":2,
       "group":9
    },
    {
       "source":"docker-compose",
       "target":"dockerfile",
       "rank":1,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"kubernetes",
       "rank":2,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"docker",
       "rank":3,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"docker run",
       "rank":4,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"docker build",
       "rank":5,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"swarm",
       "rank":6,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"code",
       "rank":7,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"docker stack",
       "rank":8,
       "level":2,
       "group":10
    },
    {
       "source":"docker-compose",
       "target":"docker compose",
       "rank":10,
       "level":2,
       "group":10
    }
 ];