// Test data for local development
export default [
    {
       "id":"docker",
       "level":1,
       "group":1
    },
    {
       "id":"kubernetes",
       "level":1,
       "group":1
    },
    {
       "id":"vm",
       "level":1,
       "group":1
    },
    {
       "id":"containerd",
       "level":1,
       "group":1
    },
    {
       "id":"container",
       "level":1,
       "group":1
    },
    {
       "id":"ec2",
       "level":1,
       "group":1
    },
    {
       "id":"virtual machine",
       "level":1,
       "group":1
    },
    {
       "id":"lambda",
       "level":1,
       "group":1
    },
    {
       "id":"podman",
       "level":1,
       "group":1
    },
    {
       "id":"docker-compose",
       "level":1,
       "group":1
    },
    {
       "id":"ecs",
       "level":2,
       "group":2
    },
    {
       "id":"docker swarm",
       "level":2,
       "group":2
    },
    {
       "id":"service fabric",
       "level":2,
       "group":2
    },
    {
       "id":"docker compose",
       "level":2,
       "group":2
    },
    {
       "id":"serverless",
       "level":2,
       "group":2
    },
    {
       "id":"fargate",
       "level":2,
       "group":2
    },
    {
       "id":"openshift",
       "level":2,
       "group":2
    },
    {
       "id":"nomad",
       "level":2,
       "group":2
    },
    {
       "id":"phere",
       "level":2,
       "group":3
    },
    {
       "id":"vdi",
       "level":2,
       "group":3
    },
    {
       "id":"dual boot",
       "level":2,
       "group":3
    },
    {
       "id":"phere client",
       "level":2,
       "group":3
    },
    {
       "id":"server",
       "level":2,
       "group":3
    },
    {
       "id":"bare metal",
       "level":2,
       "group":3
    },
    {
       "id":"vpn",
       "level":2,
       "group":3
    },
    {
       "id":"cri-o",
       "level":2,
       "group":4
    },
    {
       "id":"runc",
       "level":2,
       "group":4
    },
    {
       "id":"docker kubernetes",
       "level":2,
       "group":4
    },
    {
       "id":"moby",
       "level":2,
       "group":4
    },
    {
       "id":"docker engine",
       "level":2,
       "group":4
    },
    {
       "id":"docker-ce",
       "level":2,
       "group":4
    },
    {
       "id":"container fluid",
       "level":2,
       "group":5
    },
    {
       "id":"pod",
       "level":2,
       "group":5
    },
    {
       "id":"component react",
       "level":2,
       "group":5
    },
    {
       "id":"image",
       "level":2,
       "group":5
    },
    {
       "id":"hypervisor",
       "level":2,
       "group":5
    },
    {
       "id":"ou",
       "level":2,
       "group":5
    },
    {
       "id":"codec",
       "level":2,
       "group":5
    },
    {
       "id":"lightsail",
       "level":2,
       "group":6
    },
    {
       "id":"s3",
       "level":2,
       "group":6
    },
    {
       "id":"eks",
       "level":2,
       "group":6
    },
    {
       "id":"azure vm",
       "level":2,
       "group":6
    },
    {
       "id":"fargate pricing",
       "level":2,
       "group":6
    },
    {
       "id":"remote desktop",
       "level":2,
       "group":7
    },
    {
       "id":"emulator",
       "level":2,
       "group":7
    },
    {
       "id":"virtual desktop",
       "level":2,
       "group":7
    },
    {
       "id":"bootcamp",
       "level":2,
       "group":7
    },
    {
       "id":"virtual environment",
       "level":2,
       "group":7
    },
    {
       "id":"kappa architecture",
       "level":2,
       "group":8
    },
    {
       "id":"ec2 cost",
       "level":2,
       "group":8
    },
    {
       "id":"afr",
       "level":2,
       "group":8
    },
    {
       "id":"afr chart",
       "level":2,
       "group":8
    },
    {
       "id":"kappa light chain",
       "level":2,
       "group":8
    },
    {
       "id":"buildah",
       "level":2,
       "group":9
    },
    {
       "id":"docker performance",
       "level":2,
       "group":9
    },
    {
       "id":"singularity",
       "level":2,
       "group":9
    },
    {
       "id":"code",
       "level":2,
       "group":9
    },
    {
       "id":"docker reddit",
       "level":2,
       "group":9
    },
    {
       "id":"lxc",
       "level":2,
       "group":9
    },
    {
       "id":"dockerfile",
       "level":2,
       "group":10
    },
    {
       "id":"docker run",
       "level":2,
       "group":10
    },
    {
       "id":"docker build",
       "level":2,
       "group":10
    },
    {
       "id":"swarm",
       "level":2,
       "group":10
    },
    {
       "id":"docker stack",
       "level":2,
       "group":10
    }
 ];